DROP DATABASE AGENDA;

CREATE DATABASE AGENDA;

USE AGENDA;

CREATE TABLE CONTATOS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    IDADE INT NOT NULL,
    CREATED_AT DATE NOT NULL
);

SELECT * FROM CONTATOS;